# typed: strict

require "thor"
require "sorbet-runtime"
require "sherbet/version"
require "sherbet/startup"
require "sherbet/game"
require "sherbet/utilities"

module Sherbet
  class ThorInterface < Thor
    extend T::Sig

    # Even with just the autogenerated RBI files, this is a type error because of the wrong arity
    # desc "blah"
    desc "startup", "generates a startup idea"
    method_option :times, aliases: "-t", desc: "number of ideas to generate"
    sig { void }
    def startup
      # Now that Generator is abstract, this will be a runtime error:
      # Sherbet::Generator.new

      # Compiler error!
      # options = T.let({}, T::Hash[T.any(String, Symbol), T.untyped])
      # options[1] = 1

      Sherbet::Startup.new.run(Sherbet::Utilities.option_to_integer(options, :times, 1))

      # Run is void, so the following is not the normal return value of .run, but the
      # special T::Private::Types::Void::VOID object
      # Sherbet::Startup.new.run(Sherbet::Utilities.option_to_integer(options, :times, 1))
    end

    desc "game", "generates a new game idea"
    method_option :times, aliases: "-t", desc: "number of ideas to generate"
    sig { void }
    def game
      # This doesn't match the type signature of run, so it will be a type error:
      # Sherbet::Game.new.run
      Sherbet::Game.new.run(Sherbet::Utilities.option_to_integer(options, :times, 1))
    end
  end
end
